# suppress inspection "UnresolvedTag" for the entire file
services:
  - type: web
    name: smart-todo-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    disks:
      - name: data
        mountPath: /mnt/disk
        sizeGB: 1