# suppress inspection "UnresolvedTag" for the entire file
services:
  - type: web
    name: smart-todo-api
    env: java
    runtime: openjdk17
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/smart-todo-api-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    disks:
      - name: data
        mountPath: /mnt/disk
        sizeGB: 1